### ISSUE TITLE
JoyCon support

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#1]
Add support for JoyCons as SlimeTracker.

**Comment by techyowl** [comment]
This sounds like a glorious idea if it works. I would love to test this. I have 4 joy cons and can easily grab another pair.

**Comment by kitlith** [comment]
it sounds like this will likely be prone to drift, as the joycon only has 6DoF (accelerometer, gyroscope, no magnetometer) like the MPU-6500 or MPU-6050. however, it'll probably still make a decent testbed for people who want to try the concept but don't want to get hardware for it yet.

https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/bluetooth_hid_subcommands_notes.md#subcommand-0x43-read-imu-registers

https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/datasheets/LSM6DS3.pdf

there's a little bit of stuff in java for interacting with the joycon, but i didn't see anything targeting the IMU in particular. might be better to reference some of the non-java code, idk.

**Comment by Eirenliel** [comment]
@kitlith hang out with us on the discord :D D3adPlays currently is trying to build imu reading based on https://github.com/elgoupil/joyconLib 

6DoF is okay, slimes themselves use 6DoF fusion, BNO085 and LSM6DS3 have pretty good gyros.

**Comment by kitlith** [comment]
oh, they're not using 9dof fusion? My bad.

**Comment by dreieinss3chs** [comment]
what is with  PSMOVE  from ps3 ... not the new or ps4    they have accelerometer, gyroscope and " magnetometer

**Comment by Eirenliel** [comment]
Was actually implemented in: https://github.com/carl-anders/slimevr-wrangler
