### ISSUE TITLE
Implement more complicated knee model

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#10]
Knee can only bend along one axis (pitch), and legs don't twist much (in reality, they do, see #7, and ankle can be twisted a bit along yaw too). Ankle and thigh have always the same roll axis.

This can be used to compensate for some of #7, or just to improve precision of the leg joints. Naive approach of averaging yaw and roll using euler angles created gimbal lock (https://github.com/SlimeVR/SlimeVR-Server/commit/c2b4d30047ad00249b55b36328bb954afbe913b1), so we either need to figure out math without euler angles, or make and even more complex model for it.

**Comment by Louka3000** [comment]
Implemented in https://github.com/SlimeVR/SlimeVR-Server/pull/193 by averaging yaw and roll with Quaternion math.
