### ISSUE TITLE
VRM Model Drag & Drop area not working

### ISSUE THREAD

**Issue by ZRock35** [SlimeVR/SlimeVR-Server#1041]
Drag and drop to the active area doesn't function, no model loads. Clicking it to browse does work and loads the model correctly.
0.11.0 it works correctly
0.12.0 does not work
0.12.1 also does not work

**Comment by ImUrX** [comment]
Can be fixed via [`disable_drag_drop_handler`](https://docs.rs/tauri/2.0.0-beta.22/tauri/webview/struct.WebviewWindowBuilder.html#method.disable_drag_drop_handler)
