### ISSUE TITLE
installation linux

### ISSUE THREAD

**Issue by AnotherGitHubIG** [SlimeVR/SlimeVR-Server#1042]
whilst attempting something a little niche (although theoretically possible), i ran into an error. i am tryin to install the linux version of slime vr on a steam deck. i understand as this is more niche than just a standard linux installation, but i was wondering if anyone knows what this error means so that i might try to fix it... sorry for the lack of quality   

![PXL_20240528_190256301](https://github.com/SlimeVR/SlimeVR-Server/assets/170571740/a34c4814-edff-409b-a782-7dfca235dfde)

**Comment by ImUrX** [comment]
it's not a steam deck error, you need java 17 to run the appimage
