### ISSUE TITLE
WebSocket bridge ignores all JSON messages

### ISSUE THREAD

**Issue by rcelyte** [SlimeVR/SlimeVR-Server#1053]
In `WebSocketVRBridge.onMessage()` `message` is never actually parsed, instead attempting to process an empty JSON object:
https://github.com/SlimeVR/SlimeVR-Server/blob/e64edb76dd417432d669b699380ee97ed37399e9/server/core/src/main/java/dev/slimevr/websocketapi/WebSocketVRBridge.kt#L118-L122

**Comment by ImUrX** [comment]
lmao

**Comment by ImUrX** [comment]
Broken since https://github.com/SlimeVR/SlimeVR-Server/pull/272
