### ISSUE TITLE
Make the tracker mounting radial menu show the current selected direction

### ISSUE THREAD

**Issue by loucass003** [SlimeVR/SlimeVR-Server#1066]
Currently the radial menu only let you pick a new one, we should also show what it is currently

![image](https://github.com/SlimeVR/SlimeVR-Server/assets/3948904/107206f2-2f09-4be0-9c99-4278e46e46bb)

**Comment by ZycaR** [comment]
Pull Request to fix this issue: https://github.com/SlimeVR/SlimeVR-Server/pull/1077
![mounting-radial-menu](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/88e82e85-d70f-465f-b644-b7bff5a40478)

**Comment by ZycaR** [comment]
**Updated solution:**
Show the tracker mounting orientation on the manual mounting page for a specific body part only when all mounting orientations of the assigned trackers are the same.

**Steps to reproduce for the case to have two or more trackers on the same body part:**
- Activate the first tracker, assign it to a body part, and select a mounting orientation (e.g., Chest and Front-Left).
- Turn off the first tracker.
 - Activate the second tracker, assign it to the same body part, and select a different mounting orientation (e.g., Chest and Front-Right).
- Turn on the first tracker.

**Result:**
![manual-mounting](https://github.com/user-attachments/assets/6e54f937-12a1-4132-8cb3-ff92b898a7da)
