### ISSUE TITLE
Icon of the body part in black instead of white

### ISSUE THREAD

**Issue by loucass003** [SlimeVR/SlimeVR-Server#1074]
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/3948904/10759710-1997-41dd-8203-4c956e3fc696)

**Comment by ZycaR** [comment]
Pull Request to fix this issue:
https://github.com/SlimeVR/SlimeVR-Server/pull/1075

![image](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/a976ae58-510c-4c48-b01e-6b619995c6ad)
