### ISSUE TITLE
Add a background or a border to the 3d preview so it does not merge with the page background

### ISSUE THREAD

**Issue by loucass003** [SlimeVR/SlimeVR-Server#1079]
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/3948904/c9a02a4e-0970-4b4c-99b6-fbe0c9693b91)

**Comment by ZycaR** [comment]
@loucass003, which background is better: darker or lighter?
![obrazek](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/4d61bad6-cad3-4a53-93ff-cf6ac0fcb583)
![obrazek](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/c7435cab-8b37-4650-b0a5-c287b4b89ea2)

Additionally, we have a skeleton image on Home page (and other places). Should we apply a background for the 3D preview everywhere, or just on the Manual Body Proposition page?
![obrazek](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/1e218078-8924-48d9-a0a9-3ee0d650748d)

**Comment by loucass003** [comment]
imo lighter fits the UI more
