### ISSUE TITLE
foot trackers

### ISSUE THREAD

**Issue by lunarknight1** [SlimeVR/SlimeVR-Server#1096]
the steam tracker plugin needs the option for the foot trackers

**Comment by lunarknight1** [comment]
or add the steam ankle trackers options

**Comment by Erimelowo** [comment]
Why? Do you want both ankle and feet?

**Comment by ImUrX** [comment]
closing this issue as no info

**Comment by lunarknight1** [comment]
because i have both  foot and ankle trackers

**Comment by lunarknight1** [comment]
sorry for no response i wasn't notified that there was a response

**Comment by kruemmelbande** [comment]
There is no reason to have both. one emulated vive tracker can carry the information from the ankle and foot tracker, and to my knowledge no software supports having both an ankle and a foot tracker.
