### ISSUE TITLE
Slime Vr, couldn't find server

### ISSUE THREAD

**Issue by Loxztboy** [SlimeVR/SlimeVR-Server#1098]
So i was happily hanging out in vr when suddently i lost tracking my trackers are blinking blue and when i close and open the slime vr server client app all my tracker dissapeard, and when i tried cconeecting them again it says could not find the server.. and im stuck there so worriend somebody help! #527

**Comment by Loxztboy** [comment]
Rn one of them is saying not finding server

**Comment by Erimelowo** [comment]
As mentioned in the issue you linked, please ask via the official support channels ([Discord](https://discord.gg/slimevr) or the [official support form](https://shop.slimevr.dev/pages/support)) and we'll be happy to assist you to make sure you can use your trackers.
