### ISSUE TITLE
Implement feet touching floor

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#11]
There can be an option added for feet always trying to touch floor when users raise legs, even if they don't have feet trackers. If the ankle is slightly above the floor, foot can snap down emulating user standing on their toes. This should be an opt-in option, since it can mess up some user's inentions.

**Comment by Louka3000** [comment]
Implemented by https://github.com/SlimeVR/SlimeVR-Server/pull/609
