### ISSUE TITLE
Hand warning modal triggers if hand trackers were already on

### ISSUE THREAD

**Issue by Erimelowo** [SlimeVR/SlimeVR-Server#1120]
The hand warning modal triggers everytime even if the hand trackers were already on. It should only trigger when toggling on the hand trackers, not when it is toggled on.

https://cdn.discordapp.com/attachments/932234552431247431/1265186615278571531/slimevr_3hzHFWMyTo.mp4?ex=66a1411b&is=669fef9b&hm=8165600d1e7b6663e24ca04e82e9ff6e97d0b069a3d303e902ba31dd92dd40ee&

**Comment by ImUrX** [comment]
erimel dont use discord links pls, they timeout and are no longer usable
