### ISSUE TITLE
Set device as disconnected in SteamVR when the checkbox is unset

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#115]
There is a way to tell SteamVR through driver that the device is disconnected. Idk if it will actually work in games, but we still should use it and notify driver and SteamVR about it when user, for example, unchecks Knees in steamvr config in server.

**Comment by Louka3000** [comment]
It *should* work in games. On top of that, we also should translate the tracker to (0, 0, 0). That way we can be sure that VRChat will completely ignore those trackers (it ignores trackers at the origin with IK 2.0).

**Comment by Louka3000** [comment]
Update: just marking it as disconnected appears to have the same behaviour as completely turning off a Vive tracker, so messing with position on top is completely useless as this is enough for games (like VRChat) to completely ignore the tracker once marked as disconnected.
