### ISSUE TITLE
SlimeVR version and IP are not displayed on the mobile view

### ISSUE THREAD

**Issue by ButterscotchV** [SlimeVR/SlimeVR-Server#1164]
The version and IP do not appear when using the mobile view, this makes it kinda annoying to find that information.
![Desktop GUI](https://github.com/user-attachments/assets/bb0b4f17-6d81-4e98-a716-5b10802e91fe)
![Mobile GUI](https://github.com/user-attachments/assets/c96d2e21-c17e-4edf-9850-050bea0a1a70)

**Comment by ImUrX** [comment]
i added this on #958 but it seems it was removed by Erimel :sob: https://github.com/SlimeVR/SlimeVR-Server/pull/958/commits/a20552e35f17540635fe399bf43066a487d4007e#diff-c6e375584fb3a338d4f285d52bdbc6bfc04d28f7690d6c76470c6ef98dc3fb2a

**Comment by Erimelowo** [comment]
whaaa merge conflicts
