### ISSUE TITLE
JVM Environment Variables can crash our JVM

### ISSUE THREAD

**Issue by ButterscotchV** [SlimeVR/SlimeVR-Server#1260]
We should seriously check for `_JAVA_OPTIONS` and `JAVA_TOOL_OPTIONS` environment variables in our GUI startup, and at a minimum warn that they are set. I have seen multiple cases of people having corrupt values set for those and it is preventing launching our JVM with no obvious reason.

**Comment by VocalFan** [comment]
I'll try to smack this.
