### ISSUE TITLE
SlimeVR-Server does not run on Arch Linux with Wayland and nvidia-open drivers

### ISSUE THREAD

**Issue by quill-g** [SlimeVR/SlimeVR-Server#1263]
**Issue:**
The server application does not run properly and either closes instantly or displays a blank window.

**Steps to reproduce:**
With Wayland:
- install the AUR `slimevr-beta-bin`
- run `slimevr`
- `Error 71 (Protocol error) dispatching to Wayland display.`
- program closes

![Screenshot_20241215_121251](https://github.com/user-attachments/assets/c5be8b5b-ca95-4f4b-ab11-f48c570e309a)

Bypassing Wayland:
- run `WAYLAND_DISPLAY=0 slimevr`
- `ERROR [slimevr] Java server receiver died`
- `Failed to create GBM buffer of size 1289x709: Invalid argument`
- attempts to reconnect to webview but never recovers.

![Screenshot_20241215_121205](https://github.com/user-attachments/assets/f63d17df-3bf4-4f7f-ae37-afaef303429c)

**OS and hardware:** 
Arch Linux x86_64 running KDE Plasma 6.2.4 with Wayland.
Ryzen 7 5800X and GeForce RTX 3080 with `nvidia-open` drivers.

**Comment by ImUrX** [comment]
Failed to create GBM is easy to solve, just try one of the following https://github.com/tauri-apps/tauri/issues/9394

**Comment by ImUrX** [comment]
aside from that, this is an upstream issue

**Comment by quill-g** [comment]
Adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` got it running! Thank you!
