### ISSUE TITLE
Elbow tracking

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#14]
After https://github.com/SlimeVR/SlimeVR-OpenVR-Driver/issues/1 need to implement elbow tracking with references based on the controllers.

**Comment by Louka3000** [comment]
Implemented in https://github.com/SlimeVR/SlimeVR-Server/pull/132

Still need to integrate feeder app with server or installer tho.

**Comment by Louka3000** [comment]
The feeder app automatically starts with SteamVR if installed with the Installer.
This issue can be closed now IMO, nothing to add...

**Comment by Eirenliel** [comment]
Good stuff.

**Comment by deiteris** [comment]
New installer version needs to be published to support this change.

**Comment by Eirenliel** [comment]
Will do.
