### ISSUE TITLE
Feeder app trackers do not load null TrackerRole from config

### ISSUE THREAD

**Issue by Louka3000** [SlimeVR/SlimeVR-Server#217]
When role is NONE, feeder app trackers do not load from config properly and will instead use their role forwarded by the feeder app.
For example, if config role is NONE on the Left_Controller, it will use LEFT_CONTROLLER and ignore the fact that the role should be NONE.

I am blaming whoever removed `designation:body:none` (or whatever it was) from config and didn't make sure feeder app still worked properly :FA_FoxetteAngy:

**Comment by Eirenliel** [comment]
We should return TrackerRole.NONE, null is not set.

**Comment by Louka3000** [comment]
> We should return TrackerRole.NONE, null is not set.

The problem is that if it is not set in config, it sets it to the SteamVR role (so whatever controller or vive tracker role).
If it is not set, we need to check if the tracker exists in the config (with its ID or name idk), and, if it exists, then its role to NONE.

**Comment by TheButlah** [comment]
> :FA_FoxetteAngy:
mfw ppl use discord emojis in github (≖_≖ )
