### ISSUE TITLE
[enhancement] Serial Monitor Auto-scroll

### ISSUE THREAD

**Issue by figinternet** [SlimeVR/SlimeVR-Server#219]
In the Wifi-menu the Serial Monitor output is without auto-scroll.

For calibration of the Trackers this is handy so you can see when to move etc.
Maybe this ticket is more a extention on #112 .

At this moment I use the arduino software to see the Serial output for calibrating.

**Comment by Eirenliel** [comment]
The GUI will be replaced soon (it's already in beta https://github.com/SlimeVR/SlimeVR-GUI)
