### ISSUE TITLE
Prompt when closing if user still has tracker connected. 

### ISSUE THREAD

**Issue by Torikari** [SlimeVR/SlimeVR-Server#24]
In case of misclick or user still have tracker forgot to be turned off.

**Comment by Eirenliel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prompt when closing if user has trackers connected](https://trello.com/c/pMiIJ64J/38-prompt-when-closing-if-user-has-trackers-connected)

**Comment by Eric13246** [comment]
I would like to work on this one as a newcomer, can someone assign this to me please?

**Comment by Louka3000** [comment]
Don’t need it to be assigned for you to work on it if you want to but here you go ^^ @Eric13246

**Comment by ImUrX** [comment]
Done by #862
