### ISSUE TITLE
Stop including other codebases

### ISSUE THREAD

**Issue by ImUrX** [SlimeVR/SlimeVR-Server#246]
Using ``com/jme3`` and ``org/json`` should stop happening.
I suggest using libraries like ``ojAlgo``, ``UJMP``, Apache Common Math or [something in here](https://lessthanoptimal.github.io/Java-Matrix-Benchmark/) for replacing ``com/jme3/math``
For ``org/json`` I honestly prefer using ``jackson`` which supports ``record``s for serializing/deserializing, there is also ``Gson``.

**Comment by ButterscotchV** [comment]
Already mentioned on Discord, but we're already using **jackson** and we include **Apache Common Math**, so we can just use those
**jackson** is only left used in `WebSocketVRBridge.java` and should be simple enough to replace in that usage
