### ISSUE TITLE
add auto-scroll to serial monitor (wifi settings)

### ISSUE THREAD

**Issue by wb1016** [SlimeVR/SlimeVR-Server#257]
calibration process for IMU like MPU9250 and BMI160 prints lot of text to serial monitor, and user should keep monitoring serial output.
but due to lack of auto-scroll, the user have to keep scroll down while rotating tracker. this is quite annoying because the user should keep eyes on both tracker and serial output and scroll bar. and the user can easily miss new line on serial monitor because it is outside of the window. auto-scroll will solve this problem.

**Comment by Louka3000** [comment]
Fixed in the new GUI https://github.com/SlimeVR/SlimeVR-GUI
