### ISSUE TITLE
wifi settings (serial console) auto-scroll feature does not fully scroll to bottom

### ISSUE THREAD

**Issue by wb1016** [SlimeVR/SlimeVR-Server#259]
[video demonstration](https://youtu.be/R-bcgFMQLyg)
auto-scroll feature was [added](https://github.com/SlimeVR/SlimeVR-Server/issues/257#issuecomment-1286428246_), it supposed to work, but when rebooting via GUI causes auto-scroll leave few lines and dont scroll. when pressing reset button on tracker, it leaves 1~3 lines and dont scroll further.

**Comment by Louka3000** [comment]
The old swing GUI is no longer important.
This has been fixed in the **new** GUI, which is included in the newest release but not launched with the server by default because it’s still in development. 
The old GUI won’t be worked on, as it won’t be used for future releases.
