### ISSUE TITLE
Implement ways to reset tracker without having to open Server window.

### ISSUE THREAD

**Issue by Torikari** [SlimeVR/SlimeVR-Server#26]
Either through tapping the tracker, controller button press and gesture, or any other potential idea.

This will be a huge QOL upgrade to people who moves a lot, having the need to reset tracker in multiple succession for experimenting tracker adjustments, or unlucky enough to just have a lot of drift happening to them, worth to be in the issue here as a constant reminder.

Update 1: Tap function for BNO is too inconsistent, this has be done with gesture/button press or both.

**Comment by Eirenliel** [comment]
Is it fine if it's Fast Reset not full reset? So there is less chance to screw up alignment by body not being pefrectly straight when doing it?

**Comment by Torikari** [comment]
> Is it fine if it's Fast Reset not full reset? So there is less chance to screw up alignment by body not being pefrectly straight when doing it?

Preferably Fast Reset actually, it's been working okay for me for the past week, but it's probably good to always have a choice.

**Comment by Louka3000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reset without SlimeVR window or OVRAS keybind.](https://trello.com/c/PPRMLj2d/30-reset-without-slimevr-window-or-ovras-keybind)

**Comment by ButterscotchV** [comment]
Please re-open if this is not fully fulfilled, but I believe #328 has fulfilled this issue and will be further expanded beyond this issue with #375.

**Comment by Eirenliel** [comment]
I would love it to have integration with steam controller binding via feeder or overlay though...

**Comment by ButterscotchV** [comment]
> I would love it to have integration with steam controller binding via feeder or overlay though... But maybe it's overkill at this point, we have a bunch of options now. It's technically implemented, yes.

This is implemented in the feeder now, closing this issue.
