### ISSUE TITLE
GUI detection of motion is not sensitive enough

### ISSUE THREAD

**Issue by TheButlah** [SlimeVR/SlimeVR-Server#293]
I think that the "motion" outline on the gui should:
1. Be binary, not brighter/darker depending on how much motion
2. Should be a lot more sensitive

I tend to find that its not sensitive enough, I have to *really* move the trackers when I do it.

**Comment by nullstalgia** [comment]
I think it only checks for movement on one axis? Since when I was assembling my BNO085 carrier boards, i had to wave them long-wise to get it to light up. That, or that was just the only axis I was able to get it fast enough with. 🤔

**Comment by Louka3000** [comment]
Would using the accel work? So people can move their trackers without rotating them and it'd register movement...

**Comment by nullstalgia** [comment]
Hmm, that could also work well. As long as you keep the gyro sensing as well since not everyone has accelerometers in their DIYs.

**Comment by TheButlah** [comment]
I think both should be used
