### ISSUE TITLE
GUI - Show IP Address

### ISSUE THREAD

**Issue by lordbagel42** [SlimeVR/SlimeVR-Server#315]
It's a bit of a pain to grab the IP address of a quest 2. With more and more people switching to hosting the server on it, it should be made easier. A little box that showed the IP of the server would be a great solution, much like the version counter in the top left already. If the SlimeVR server could also print out the IP on startup, that would also be great, as once you start it it's obvious what the IP is.

**Comment by ImUrX** [comment]
The current returned IP is the loopback one, it should show the current used interface. There is no Best Way:tm: to do this but [here is a way](https://stackoverflow.com/a/41232639) at least
