### ISSUE TITLE
Use a global panic handler in tauri that displays a native popup

### ISSUE THREAD

**Issue by TheButlah** [SlimeVR/SlimeVR-Server#322]
We recently added (or are adding?) native dialog popups that occur in the case of errors that cannot be displayed in the tauri frontend (i.e. rust errors *before* webview).

We should also have a global panic handler that uses this dialog system.

**Comment by ImUrX** [comment]
I don't understand, doesn't the current implementation [already implement a panic hook](https://github.com/SlimeVR/SlimeVR-Server/blob/main/gui/src-tauri/src/main.rs#L77)?
What else would be needed? (btw [``#[panic_handler]`` is a ``no_std`` thing](https://doc.rust-lang.org/nomicon/panic-handler.html))

**Comment by TheButlah** [comment]
Lol I'm just blind apparently
