### ISSUE TITLE
Have seperate toggles for sending and receiving OSC?

### ISSUE THREAD

**Issue by Louka3000** [SlimeVR/SlimeVR-Server#325]
Discussion: should we?
- This would make it so users don’t have to worry about clogging ports when, for example, not receiving any data.
- Might add some confusion tho.
- Also maybe too late to easily do it because of protocol?

**Comment by Louka3000** [comment]
@TheButlah @loucass003

**Comment by TheButlah** [comment]
by toggles, do you mean should we have both the steamvr and osc sections?
![image](https://user-images.githubusercontent.com/6969415/204969836-17ea84c4-ad3d-4d1d-a844-0d1a74e55ed9.png)
![image](https://user-images.githubusercontent.com/6969415/204969855-3dfb3508-c65b-4c79-8cea-0ebc543fafe1.png)

I didn't understand what you were referring to.

**Comment by Louka3000** [comment]
No, I making the single OSC "Enable" toggle into 2 "Enable sending" and "Enable receiving" toggles. Nothing to do with SteamVR.

**Comment by TheButlah** [comment]
Too many settings bad for users. I'm not worried about hogging another port, or sending a little bit of extraneous data that will never arrive

**Comment by ButterscotchV** [comment]
Could be nice if it's hidden behind advanced settings or whatever, keep it simple for the user unless they specify that they want more

**Comment by TheButlah** [comment]
I would agree if it actually did anything useful - but I don't think it really does

**Comment by Louka3000** [comment]
Users **could** just put a random number in, for example, "Port In" if they don't wanna receive data.
But at the same time, that could potentially break other programs (altho probably extremely unlikely), and it's not a pretty user-friendly way to do it IMO.

Also need to consider when users would not want to receive data ig... Support for stuff like https://github.com/SlimeVR/SlimeVR-Server/issues/323 would just not have any OSCSender (thus no Port Out in GUI)... There might not be any situation where SlimeVR allows to user to receive or send data while the user wouldn't want one of those...

**Comment by TheButlah** [comment]
protocol != GUI
GUI can have a value of -1 and do something with the protocol.

**Comment by Louka3000** [comment]
Yes but that would require having 2 booleans in the protocol. I'm just saying it can't work with the current protocol and GUI.

**Comment by Louka3000** [comment]
Doesn't seem like this is interesting, as clogging up a port probably isn't a concern
