### ISSUE TITLE
Have Serial Console in UI ignore Valve Index Bluetooth Adapter COM Port

### ISSUE THREAD

**Issue by nullstalgia** [SlimeVR/SlimeVR-Server#362]
![image](https://user-images.githubusercontent.com/20761757/206889224-517b18b3-729c-46a4-9c93-2e3b692f3ab9.png)

Here's the PID/VID reported by Windows.

**Comment by unlogisch04** [comment]
Currently the upstream library does not support it.
https://github.com/Fazecast/jSerialComm/issues/460

**Comment by Louka3000** [comment]
With the new GUI this completely breaks serial and even crashes the server. The hardware IDs given are the same I have
`USB\VID_28DE&PID_2102&REV_0100&MI_01`
`USB\VID_28DE&PID_2102&MI_01`

**Comment by raymondh2** [comment]
Would it be possible to add a temporary work around of being able to turn off detection of USB serial devices?

**Comment by ImUrX** [comment]
i know how to fix this, im waiting for #756
