### ISSUE TITLE
Automatically disable Leg tweaks when using Autobone or Manual Body proportions

### ISSUE THREAD

**Issue by ZRock35** [SlimeVR/SlimeVR-Server#364]
Proportions have problems if it is active when doing those things

**Comment by loucass003** [comment]
![image](https://user-images.githubusercontent.com/3948904/206927695-1b62ff41-061d-462c-9fb8-44a4fd2a9744.png)

**Comment by ButterscotchV** [comment]
> Proportions have problems if it is active when doing those things

AutoBone is not affected by this as it already internally disables it, though when you try out your proportions after it'll affect that but idk that's just user error? We could add a "proportions mode" where it just disables any enhancements and whatnot for testing them or demonstrating them.

**Comment by Spazznyan** [comment]
This was added yeh? close this one plx

**Comment by Louka3000** [comment]
Implemented in https://github.com/SlimeVR/SlimeVR-Server/pull/627
