### ISSUE TITLE
Extensions showing up as the same tracking point

### ISSUE THREAD

**Issue by NWBx01** [SlimeVR/SlimeVR-Server#365]
![Screenshot 2022-12-11 160737](https://user-images.githubusercontent.com/21149527/206930268-fb04199a-6c82-4ce7-b23e-898f98f1c071.png)
Trackers with extensions often show up as being of the same tracking point. This isn't a permanent issue; trackers can still be reassigned, however.

**Comment by nullstalgia** [comment]
This seems most common when one of the IMUs was disconnected/having an issue when the tracker last connected, in my experience.

**Comment by Louka3000** [comment]
Pretty sure this was fixed a bit ago in a PR. Open again if still happening in latest releases.
