### ISSUE TITLE
Rework reset to use vectors instead of euler angles

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#37]
Reset and fast reset should use vectors instead of euler angles to align yaw properly, otherwhise they hit gimbal lock in some positions, especially fast reset that should be usable in any position. Should match forward vector of HMD with forward vectors of the trackers in both modes.

**Comment by ImUrX** [comment]
@Louka3000 this is done, right?

**Comment by Louka3000** [comment]
There’s certain things that could be changed with the reset math that I talked to with AxisAngle, but that’s outside the scope of this issue (avoiding gimbal lock).
