### ISSUE TITLE
Trackers aren’t connecting to vrchat Osc property 

### ISSUE THREAD

**Issue by Gram161** [SlimeVR/SlimeVR-Server#385]
I set up everything properly in slimevr and when I go to calibrate in vrchat Osc for standalone full body some of the trackers stop working or they track the wrong body parts. Like my leg tracker would track my chest even tho I don’t have a chest tracker on

**Comment by TheButlah** [comment]
> I set up everything properly in slimevr
Can you provide screenshots of your mounting assignments? Also, did you stand upright and double tap your chest tracker to calibrate the pose *before* calibrating in vrchat?

What version are you using? Please provide the commit hash or git tag. Did you install via the installer or did you download it directly?

Also you may find that #support-forum in the [discord](discord.gg/SlimeVR) will be more helpful for you - github is used more for feature tracking and technical bug reports.
