### ISSUE TITLE
[Server] Upload firmware via OTA

### ISSUE THREAD

**Issue by Dounx** [SlimeVR/SlimeVR-Server#405]
Can we add a feature to update each connected tracker via OTA?

**Comment by Dounx** [comment]
1.  Select the firmware
2.  Select the conntected trackers
3.  Click Upload button

**Comment by Dounx** [comment]
I found a [firmware-update](https://github.com/SlimeVR/SlimeVR-Server/tree/firmware-update) branch,  will it implement the OTA upgrade function? @loucass003

**Comment by Kamilake** [comment]
> I found a [firmware-update](https://github.com/SlimeVR/SlimeVR-Server/tree/firmware-update) branch, will it implement the OTA upgrade function?

I made this as a simple batch script.
that automatically detect the ip addr, selects and flash firmware with OTA, and then the tracker reboots itself.   

If you think this code is useful for you, I will release it with an English(or your lang)!
(currently translated into Korean)

**Comment by Dounx** [comment]
> > I found a [firmware-update](https://github.com/SlimeVR/SlimeVR-Server/tree/firmware-update) branch, will it implement the OTA upgrade function?
> 
> 
> 
> I made this as a simple batch script.
> 
> that automatically detect the ip addr, selects and flash firmware with OTA, and then the tracker reboots itself.   
> 
> 
> 
> If you think this code is useful for you, I will release it with an English(or your lang)!
> 
> (currently translated into Korean)

This is exactly the functionality I want, I would like to refer to the implementation if possible, English is fine.

**Comment by Kamilake** [comment]
> This is exactly the functionality I want, I would like to refer to the implementation if possible, English is fine.

If it's useful for you, I'll proceed with the work!

https://github.com/Kamilake/FineMotion_OTA_Uploader

Without python dep:
https://cdn.discordapp.com/attachments/1002402449954451466/1064140974495891476/0.3.1a_FineMotion_Updater.zip

**Comment by Kamilake** [comment]
I just finished a basic translation and some tweaks! @Dounx

**Comment by Dounx** [comment]
> I just finished a basic translation and some tweaks! @Dounx (It's a machine translation, but I'd appreciate it if you could review it.)

Thx, I will try to port your code to SlimeVR-Server project later.
