### ISSUE TITLE
Trackers don't move

### ISSUE THREAD

**Issue by CassieCatYT** [SlimeVR/SlimeVR-Server#420]
The trackers (I'm using phones with accelerometers and OWOTrack) don't move, only rotate in SteamVR

**Comment by Louka3000** [comment]
Hi, please make sure you’re following the docs for setting up SlimeVR: https://docs.slimevr.dev/server-setup/slimevr-setup.html
If you need additional support, please create a post in our support forum in our discord: https://discord.gg/slimevr
