### ISSUE TITLE
No feedback when triggering tap gestures.

### ISSUE THREAD

**Issue by nullstalgia** [SlimeVR/SlimeVR-Server#422]
Howdy howdy.

When using the new and (wonderful) tap reset, it's hard to tell if my taps actually went through and if I should stay in the pose for the duration of time I set for the delay, or if I should tap again, or when I can put my arms down if I have arm trackers.

A beep of some kind when the gesture is recognized, and another when the reset has occurred would be ideal.

**Comment by Eirenliel** [comment]
The feature that plays a sound on reset was requested long ago, we even have a meow sound recorded for this. If someone goes to implement it, please ask me for the audio file!

**Comment by marcozzxx810** [comment]
I will take this!

**Comment by Louka3000** [comment]
Closed by https://github.com/SlimeVR/SlimeVR-Server/pull/576
