### ISSUE TITLE
SlimeVR is requesting that you read this github issue 🥲

### ISSUE THREAD

**Issue by TheButlah** [SlimeVR/SlimeVR-Server#424]
Hi @ThePheonixGuy

I'm assuming you turned off notifications for #308. But you are the only person left who still needs to fix their comment. The comment you left says 

> "Eiren Rain and SlimeVR Contributors".

**BUT it should say instead**
> "Eiren Rain and SlimeVR Contributors" or "SlimeVR Contributors".

We cannot proceed with the relicensing until you do this 😅

**Comment by TheDevMinerTV** [comment]
the linked got a comment by this person earlier today - closing
