### ISSUE TITLE
One leg support, remove multiple skeletons

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#44]
Add support for one leg. For this multiple skeletons (SkeletonWithWaist, SkeletonWithLegs) should be merged in one and be able to be used with any configuration of trackers, just returning warnings when chains are missing. This will also be a nice refactoring.

**Comment by Louka3000** [comment]
The skeleton doesn’t return warnings when a tracker is missing, but it still works by not moving or defaulting to another tracker.
What would support for one leg be tho?
The refactor/merging skeleton class was implemented in #95

**Comment by Eirenliel** [comment]
This is true, @ButterscotchVanilla did a good job!
