### ISSUE TITLE
Factory Reset button in Serial Console could have a pop up warning about what it does

### ISSUE THREAD

**Issue by ZRock35** [SlimeVR/SlimeVR-Server#440]
Users tend to click everything, and this could be one where we want to caution them not to just push forward blindly. Calibration and wi-fi creds get deleted with this button, so it could be a problem.

**Comment by ZRock35** [comment]
![image](https://user-images.githubusercontent.com/91239122/213070277-86ac6549-a1fd-4a14-a5b4-dad98ee87c65.png)

**Comment by unlogisch04** [comment]
@0forks factory reset should not delete the firmware. Only all configurations and calibrations on the flash of the esp.
