### ISSUE TITLE
Make reset pose t-pose instead of i-pose

### ISSUE THREAD

**Issue by Louka3000** [SlimeVR/SlimeVR-Server#481]
Arms resetting in i-pose is causing a lot of confusion, and they should thus use t-pose, just like VRChat does.
T-pose is also more common than i-pose anyway.
having a toggle to switch between ipose and tpose would be nice too.

**Comment by Loler920a** [comment]
Ideally it would be best to have it on a toggle as, perfectly tposing can be tricky without seeing yourself sometimes. I pose can produce more consistent results as well as be less awkward resetting in the middle of a social context (t poses mid conversation)
