### ISSUE TITLE
Trackers aren't detected

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#502]
On Poly's PC literally nothing happen when you plug in the tracker, even though the serial exists.

![img](https://cdn.discordapp.com/attachments/946392672791318528/1067112371014873168/image.png)
![img](https://cdn.discordapp.com/attachments/946392672791318528/1067112456658370571/image.png)
![img](https://cdn.discordapp.com/attachments/946392672791318528/1067113024495816785/image.png)
![img](https://cdn.discordapp.com/attachments/946392672791318528/1067113388930519130/image.png)

On my laptop I see a popup but it can't provision the tracker.

![image](https://user-images.githubusercontent.com/1257939/214099168-8588c2af-bf2e-4f84-a848-bf52b6707d22.png)

Even though I can actually open serial console and send GET INFO.

No idea how to even start debugging it.

**Comment by Eirenliel** [comment]
After random figieting it provisioned on my laptop. I had to reboot the tracker for it to send commands, but I can't find where in the code it looks for boot sequence or anything.

**Comment by 0forks** [comment]
Also if the "connect trackers" window is opened for a some period of time, even just 5 minutes, it starts a lot of connect loops, resulting in many connections per second.
```
15:05:16 [INFO] Trying to open:Auto  auto: true
15:05:16 [INFO] Trying to open:Auto  auto: true
15:05:16 [INFO] Trying to open:Auto  auto: true
... 50+ lines
```
