### ISSUE TITLE
Neck tracker needs a warning upon assignment, indicating potential lethal choking danger of improper neck strap/collar.

### ISSUE THREAD

**Issue by ZRock35** [SlimeVR/SlimeVR-Server#510]
Since users will want to try everything, this is important to put so that people are aware of the risk of using the neck tracker. 

WARNING: Neck tracker can be deadly if too tight of a strap cuts off circulation to the head!

**Comment by TheDevMinerTV** [comment]
I think people will know when a choker is too tight :joy:
also, kinky.
