### ISSUE TITLE
Slime Vr Client Not detecting Trackers

### ISSUE THREAD

**Issue by backspacestud** [SlimeVR/SlimeVR-Server#527]
Hello,

I recently finished all steps  up until it was time to use the VR server. I have used the client to put in the wifi, hard coded it in the firmware, and used both windows and linux clients. On top of that I have used an entire other router and i know its not an issue with the wifi because it connects to the server. If there is an easy and known fix to this issue let me know, The only other thing i can thing of being is that because the sensors are not working it does not connect? It could be a soldering issue or a fried board so i will try to make another but i would like conformation/ extra info to help me troubleshoot. Thank you!

![Screenshot_20230128_170605](https://user-images.githubusercontent.com/101374988/215298334-f3e7ebf8-abee-41d7-ac9e-7cc0c44cc94a.png)

**Comment by TheButlah** [comment]
Without a reliable way for us to reproduce this, its unlikely for us to be able to find the cause of the issue. The support forum in discord is probably a better venue to troubleshoot this unless there are more tangible leads. https://discord.com/channels/817184208525983775/1025104406393405491
