### ISSUE TITLE
Step numbers in step-based processes are all linked together

### ISSUE THREAD

**Issue by ButterscotchV** [SlimeVR/SlimeVR-Server#537]
The title is a bit confusing, so I'll just provide some screenshots that will explain everything:

![image](https://user-images.githubusercontent.com/5095026/215611355-a0178836-8ec2-4c2f-b83d-075682ba8974.png)
![image](https://user-images.githubusercontent.com/5095026/215611428-8b2ffd49-6259-4958-abe2-504aab7253bb.png)

**Comment by loucass003** [comment]
heck
