### ISSUE TITLE
Fix tracker rotation unit tests

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#55]
We have empirically concluded that current reset and adjustment algorithm works fine, but it doesn't pass unit tests. We need to rewrite tests from scratch that would have rigorous proof of it working; or we need to adjust test to pass for current reset algorithm.

**Comment by Eirenliel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rotation unit tests](https://trello.com/c/L6MZarZd/37-rotation-unit-tests)

**Comment by Louka3000** [comment]
That’s a very old issue, unit tests for resets works fine
