### ISSUE TITLE
Bundle and publish server release when a tag is created

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#585]
Right now almost everything is already gets built on tag creation, but there are few things that needs finalizing:

* [ ] Bundle windows build
* [ ] Create draft release when a tag is created
* [ ] Upload required artifacts to the release
* [ ] Make sure everything is named properly

**Comment by marcozzxx810** [comment]
Can we automate the step of publishing the app to flathub

**Comment by ImUrX** [comment]
We could, but the toolchain used is too young and prone to breaking.
This ends up requiring someone to maintain it, like most package managers :/

**Comment by Eirenliel** [comment]
Other changes to CI:

* [ ] Run bundle only after tests
* [ ] Run tests only after build

**Comment by Eirenliel** [comment]
* [ ] Do not run bundle unless manualy ran or when a tag is created, it takes ages for PRs to bundle even though we don't need it

**Comment by ImUrX** [comment]
Tests and building already take 2 minutes each, having them in dependence would make it 4m to finish actions. I can make bundle job depend on tests and build though.

**Comment by Eirenliel** [comment]
Well my idea was since test requires build it can re-use the build artifact? It would also be nice for stuff to fail faster, right now each test starts even when some other tests fail, but we don't really need it in most cases, since if one fails we see the problem. Making bundle depend on others is the minimum, yeah.

Also clean up artifacts generated too. Right now linux and mac are bundled in server action, but windows gui is built in gui action while windows server is build in server action...

**Comment by ImUrX** [comment]
every OS binary is built on GUI action, I think I forgot to add a macOS artifact though.

I don't think the artifact reuse will work, because the server artifact is an uber jar one. Let's try without test needing for build for now
