### ISSUE TITLE
Work without waist and chest trackers

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#61]
Right now it works if you don't have waist or chest trackers, but it doesn't rotate at all. Yaw of waist and chest should match yaw of the headset if chest and waist trackers are missing probably. This is bad either way, but it will let test some stuff more easily without the need for full set of slimevr.

Legs with missing trackers should also match their yaw to the previous tracker in the chain.

**Comment by Louka3000** [comment]
solved in https://github.com/SlimeVR/SlimeVR-Server/pull/138
