### ISSUE TITLE
Tracker warning with waist/hip only

### ISSUE THREAD

**Issue by Louka3000** [SlimeVR/SlimeVR-Server#612]
Using a waist or hip tracker only (no legs), the user should not get a warning about a missing chest tracker.

**Comment by Eirenliel** [comment]
Why? Isn't it still recommended to use chest tracker?

**Comment by Louka3000** [comment]
No, quit the opposite. 
When doing hip-only tracking, the spine won’t bend; the user will always be standing up (or else VRChat breaks their body due to custom sitting and lying animations). Thus, hip rotation should be prioritized over good spine tracking
