### ISSUE TITLE
[GUI] Mounting reset and mounting position doesn't have any feedback if they're done correct

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#622]
Right now it's impossible to know if you scrwed up mounting reset until you get into VRChat and see that everything is wrong.

We need to add a 3D character model on mounting screen and maybe somewhere else so that user could try their body movements without the need to switch to VR and then figure out what's wrong with them.

**Comment by Eirenliel** [comment]
Different solutions are acceptable to this, but right now it's impossible to understand if you did something wrong, which is possible to do.

**Comment by ImUrX** [comment]
I think this can be closed with skeleton preview now?
