### ISSUE TITLE
The GUI build process exports Linux and Mac binaries in the same file, causing issues.

### ISSUE THREAD

**Issue by Riku5543** [SlimeVR/SlimeVR-Server#634]
Hi there. I checked the binary in SlimeVR-GUI-Linux.zip from a couple of the latest releases and discovered that the binary type is like this:
`slimevr: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>`
IIRC, Mach-O binaries are for MacOS. I checked the build process on the "Upload a build artifact" step and discovered that both the Mac and Linux build steps output to an artifact called "SlimeVR-GUI-Linux" which means that the MacOS version is overwriting the Linux version.
Sorry if my investigation was incorrect, hope it helps.

**Comment by ImUrX** [comment]
Yes this is true, I noticed it and never fixed it :laughing:
