### ISSUE TITLE
[Feature Request] Notify User That SlimeVR Addon is Disabled in SteamVR

### ISSUE THREAD

**Issue by NWBx01** [SlimeVR/SlimeVR-Server#653]
Oftentimes when SteamVR crashes it will disable addons, such as SlimeVR. For a less experienced user this can be rather confusing as to why their trackers would suddenly stop working.

Ideally, then, the SlimeVR Server should notify the user that the SlimeVR addon is not currently enabled in SteamVR.

**Comment by Eirenliel** [comment]
Good feature request. We should add it to the list of warnings on the main screen. It should have an option disable the warning if the user doesn't use SteamVR.
