### ISSUE TITLE
Default orientation for some trackers

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Server#654]
Default mounting orientations for some trackers should be set according to our recommendations, not just front. Currently it's: left upper arm, left lower arm, left hand - left; right upper arm, right lower arm, right hand - right; hip - right.

**Comment by Louka3000** [comment]
Chest, waist and hip should be front! Not side!
Thighs: front
Ankles: side (outwards)

**Comment by Eirenliel** [comment]
Well The Docs™ recommends waist on the side: https://docs.slimevr.dev/server/putting-on-trackers.html. Which I belive is the leftower from when it was factually hip... We should get to a consensus, recommend this to users and use as a default, since Poly and Uriel are designing the page in wizard about putting trackers on.

**Comment by Louka3000** [comment]
That’s just your picture that I didn’t remove. We could remove them now.
![E7316870-242A-4418-A544-F193C33D6585](https://user-images.githubusercontent.com/20461725/230214559-d3403dcb-8647-4b70-8e6c-6dbcb5d72ede.jpeg)

**Comment by Eirenliel** [comment]
Okay. Then front. Thought it still says "or left", but yea...

**Comment by Eirenliel** [comment]
> #679 should be completed for this

Why? No.

**Comment by Louka3000** [comment]
> > #679 should be completed for this
> 
> Why? No.

So that ankles and upper arms can be diagonal

**Comment by Eirenliel** [comment]
We just need them to be on the side by default it's way better than front already. Please don't block this feature by another feature (that I honestly don't think should exist at all). We need something that is better than current one. If we add diagonal mounting in the future (I don't think we should), we can change defaults.
