### ISSUE TITLE
"New serial device detected" pops up for non ESP devices

### ISSUE THREAD

**Issue by TheDevMinerTV** [SlimeVR/SlimeVR-Server#694]
Somewhere between v0.6.8 and v0.7.1 a bug got introduced, that the "New serial device detected" popup appears for non ESP devices, for example my keyboard. This is really annoying because it happens every time I restart the server or reconnect my keyboard.

**Comment by Eirenliel** [comment]
Our system to choose which devices are slimes is very bad, we need better solutions than just to filter by device name.

**Comment by ImUrX** [comment]
Connected to #362, we need PID and VID tbh
