### ISSUE TITLE
Use path alias instead of relative path in GUI project

### ISSUE THREAD

**Issue by marcozzxx810** [SlimeVR/SlimeVR-Server#764]
Using a relative path seems hard to be understood, For example:

https://github.com/marcozzxx810/SlimeVR-Server/blob/main/gui/src/components/onboarding/pages/ConnectTracker.tsx#L12

Proposed solution

- [ ] use `@` to indicate root path for GUI

Current
```ts
import { useLayout } from '../../../hooks/layout';
import { useOnboarding } from '../../../hooks/onboarding';
```
Later
```ts
import { useLayout } from '@/hooks/layout';
import { useOnboarding } from '@/hooks/onboarding';
```

**Comment by ImUrX** [comment]
you mean `@hooks/` i guess, does the editor do this when auto-importing a new module or does it still use relative pathing? Can we enforce this through eslint?

**Comment by marcozzxx810** [comment]
I mean '@/hooks' so we have '@' pointing to gui folder. It depends on your LSP but editor with intellisense should be able to pick up tsconfig


For eslint, https://www.npmjs.com/package/eslint-import-resolver-typescript  I am not so certain about can we enforce it

**Comment by ImUrX** [comment]
i meant, auto-imports will prefer using the aliases or relative paths?

**Comment by marcozzxx810** [comment]
vscode will prefer the alias

**Comment by TheDevMinerTV** [comment]
> vscode will prefer the alias

It depends on what the user configured, though we can override this by including a `.vscode` folder with the new settings.

**Comment by ImUrX** [comment]
then its fine, sure :+1:
