### ISSUE TITLE
Explicit step during body proportions to set height

### ISSUE THREAD

**Issue by yoyobuae** [SlimeVR/SlimeVR-Server#788]
Add an explicit step to either manually input or automatically measure user's height as part of the body proportions section.

Currently this is lumped together with "Reset all proportions" button, which does automatic measurement without telling the user that they need to have the VR headset on to be automatically measured and they are not told what that measured height was (so they can't check if the measurement was wrong). This results in new users often having "all my trackers are inside my head" issues and having to be told to "Reset all proportions".

My suggestion is to have height measurement as an explicit step which can be done either manually (ie. input height as a number) or automatically (by measuring using VR headset). The user should explicitly be told to wear their VR headset when using automatic height measurement and then told what the measured height was so they can check it is correct.

**Comment by ImUrX** [comment]
Fixed by #776
