### ISSUE TITLE
Body config 'profiles'

### ISSUE THREAD

**Issue by calliePepper** [SlimeVR/SlimeVR-Server#82]
The ability to save and reload body config profiles would be invaluable for households with multiple people who use the same VR set up instead of having to write down and re-input their body config set up.

While the server/firmware is being developed this would also be incredibly useful for members of the DIY community like thebutlah who has to use a specific set up for dancing to isolate the hips but it doesn't work for day to day activities that involve bending the spine

**Comment by ButterscotchVanilla** [comment]
I believe this is a duplicate of issue #38

**Comment by calliePepper** [comment]
You are incredibly correct, I missed it on a quick scan!
