### ISSUE TITLE
When a rotation vector of nan is received, the application needs to be restarted

### ISSUE THREAD

**Issue by wigwagwent** [SlimeVR/SlimeVR-Server#829]
So when the imu reports a NaN in the rotation it will not go away once the imu starts sending real data again. For example you short the imu or an incorrect calibration gets loaded to the imu it can return NaN. When the sever gets this it will break the the preview (no tracker will show) and will break the rotation display (won't update for that tracker). After the tracker starts sending real data (raw rotation does not break) a full reset will not fix the main rotation and it will still display NaN. The only way I have found to get rotation from that tracker again is to restart the server.

![image](https://github.com/SlimeVR/SlimeVR-Server/assets/66268000/7982b9d1-d478-454a-9b44-89ea20f51d73)

**Comment by wigwagwent** [comment]
I had this problem developing for an imu, a day later another discord user also had the same problem when using there mpu6050. They found out when you switch out of dev mode it resets the server so it will work again without having to restart the application.

**Comment by Louka3000** [comment]
Solved by https://github.com/SlimeVR/SlimeVR-Server/pull/832
