### ISSUE TITLE
Closing the SlimeVR-Server causes tracker to be stuck on "connecting to server"

### ISSUE THREAD

**Issue by namakeingo** [SlimeVR/SlimeVR-Server#863]
**Issue:**
When using a 7+3 or 10+6 set, restarting the SlimeVR-Server app while the trackers are on and connected causes the majority of the trackers to get stuck at "connection to server". Turning the "stuck" trackers OFF does not solve the issue as they will boot again in that "stuck" state. The only solution to get them unstuck is to turn off ALL trackers, close and reopen SlimeVr-Server and turn the trackers on again.

**Possible mitigation of the issue:**
SlimeVR-Server could minimize to tray on "close" of the app so that trackers can keep communicating with the server. Shut down of the app should only be by right-clicking on the tray icon of SlimeVR-Server and selecting "exit". By applying this change the issue is mitigated as shut down of the server cannot happen by mistake.
See https://github.com/SlimeVR/SlimeVR-Server/issues/864

**Recreation steps:**
Using a 7+3 or 10+6 set

1. Open SlimeVR-Server
2. Turn on and connect all trackers
3. Close SlimeVR-Server
4. Open SlimeVR-Server

_At this stage App will show only a limited number of trackers connected. All trackers that are not connected will have the status LED blinking with a single really short blink at a few seconds interval_
_Restarting the problematic trackers will not fix the issue as they will fail to connect again_
_Connecing the problematic trackers via USB will fail at connecting saying "Cannot connect to SlimeVR server"_

**Comment by Eirenliel** [comment]
> Suggested solution or mitigation of the issue:
> SlimeVR-Server should minimize to tray on "close" of the app so that trackers can keep communicating with the server. Shut down of the app should only be by right-clicking on the tray icon of SlimeVR-Server and selecting "exit". By applying this change the issue is mitigated as shut down of the server cannot happen by mistake.

Sorry, this is clearly a wrong solution :D The issue should be fixed. If there is a request for server to be minimized on close, the issue should be created for this specifically unrelated to the bug with the trackers.

**Comment by namakeingo** [comment]
> > Suggested solution or mitigation of the issue:
> > SlimeVR-Server should minimize to tray on "close" of the app so that trackers can keep communicating with the server. Shut down of the app should only be by right-clicking on the tray icon of SlimeVR-Server and selecting "exit". By applying this change the issue is mitigated as shut down of the server cannot happen by mistake.
> 
> Sorry, this is clearly a wrong solution :D The issue should be fixed. If there is a request for server to be minimized on close, the issue should be created for this specifically unrelated to the bug with the trackers.

You are right, that is why I mentioned "_or mitigation of the issue_", if closure of the app is made more intentional then the issue is less likely to happen. If the app is not closed while in use all is fine. To be fair the only reason I found out this issue is that I distractedly closed the app.
In any case I raised a separate issue for "minimise to tray" https://github.com/SlimeVR/SlimeVR-Server/issues/864

**Comment by ButterscotchV** [comment]
Unable to reproduce this issue with v0.10.1, it sounds like an issue with your networking or something to me, do you have any errors in the logs that could be related?
https://github.com/SlimeVR/SlimeVR-Server/assets/5095026/0ad2064b-86ca-431d-a9f8-ddf2cab4d8be

**Comment by namakeingo** [comment]
My network is very simple. Just a modem+router combo for fiber connection. My PC is connected via ethernet. The trackers are on 2.5 wifi. The only weirdness if anything is that I use virtual desktop to connect my quest 2.
In any case I'll try again and check out the logs too as soon as I can.

**Comment by namakeingo** [comment]
looks to be an issue with my firewall software even tho I literally checked before raising the issue. Sorry about this. Closing the issue
