### ISSUE TITLE
Can a mobile phone be used as a head-mounted display?可以实现手机当头显吗？

### ISSUE THREAD

**Issue by dongdongdonglin** [SlimeVR/SlimeVR-Server#919]
I tried installing owoTrack on my phone to set up the control head, but it didn’t seem to work.
试了手机安装owoTrack设置控制头，但是好像没有用
Who can teach me, thanks
谁能教一下，感谢

**Comment by Louka3000** [comment]
Are you able to join our Discord server? discord.gg/slimevr
In it, we have a #owotrack channel for owotrack help/tech support.
