### ISSUE TITLE
Stuck on Connecting to the server

### ISSUE THREAD

**Issue by Lumince** [SlimeVR/SlimeVR-Server#949]
I performed a reinstall of windows today and I get this error when attempting to run the server after using the installer from here.
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/10453497/b5bb4506-a0ad-4fe6-932f-c994f3e2b7f7)
I get this when I bring up the console.
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/10453497/c668d16f-1ed0-4b20-bcc8-dcf4a28537ad)

**Comment by Lumince** [comment]
[slimevr_rCURRENT.log](https://github.com/SlimeVR/SlimeVR-Server/files/14425384/slimevr_rCURRENT.log)
Here is the whole log file as well.

**Comment by ImUrX** [comment]
We need the server's log which should be called something like `log_last_X.log`

**Comment by Lumince** [comment]
[log_last_0.log](https://github.com/SlimeVR/SlimeVR-Server/files/14425685/log_last_0.log)
Its quite empty

**Comment by Lumince** [comment]
So I think that there is some left over data that slimeVR server since I did not get the initial setup screen when installing the program?
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/10453497/7316bcff-dbc9-4d4b-8dd0-a13a2e0457db)
Is there any way to fully reset the program from the start?

**Comment by unlogisch04** [comment]
to remove all settings delete the following folders:
%appdata%\dev.slimevr.SlimeVR
%localappdata%\dev.slimevr.SlimeVR

**Comment by Lumince** [comment]
Yea I tried deleting those as well but the issue still remains. When I installed the program onto my reinstall of windows I did not get the initial setup wizard screen. So theres nothing set in the first place

**Comment by unlogisch04** [comment]
Make sure you have installed Visual C++ ( https://github.com/SlimeVR/SlimeVR-Installer/issues/43 )
Did you not get any popup about a error, that a port is in use? (Some ppl reported that on windows 11 with some container features enabled)

**Comment by Lumince** [comment]
I have that installed and I still get the same behavior. No pop ups. No errors. I havent even changed any settings since I reinstalled windows this morning. It just refuses to show me the setup wizard or do anything but the above errors

**Comment by ImUrX** [comment]
You should check your firewall, as the connection refused part is kinda sus, maybe try https://github.com/SlimeVR/SlimeVR-Server/issues/674#issuecomment-1545860650

**Comment by Lumince** [comment]
The server isnt even starting. Seems like its either failing to launch or its crashing?

**Comment by Lumince** [comment]
The more I look into it. The more it seems like everyone points towards windows being the issue here and not the program?.... If anyone else has any suggestions, that would be great. I got full body tracking and I can't even use it :(

**Comment by ImUrX** [comment]
yeah, maybe reinstall windows, sorry qwq, or maybe you are lucky with the following commands
```
sfc /scannow
DISM /Online /Cleanup-Image /CheckHealth
DISM /Online /Cleanup-Image /ScanHealth
DISM /Online /Cleanup-Image /RestoreHealth
```

**Comment by Lumince** [comment]
Yeaaaa looks like I will have to reinstall windows AGAIN. Those commands found no corruption at all so something is just screwed up.
