### ISSUE TITLE
Add toggle to mirror tracking/VMC 

### ISSUE THREAD

**Issue by Erimelowo** [SlimeVR/SlimeVR-Server#952]
Either mirror the whole tracking from the skeleton (would include BVH), or just mirror while retargetting for VMC.
For applications that don't have a way to mirror tracking for vtubers.

**Comment by Louka3000** [comment]
Would like thoughts about if this should be a VMC-only feature or apply to the whole tracking

**Comment by CrystalSpore** [comment]
Adding my voice as somebody who would be interested in this feature. Especially if it could take other VMC inputs & mirror those as well
