### ISSUE TITLE
Unable to connect a second set of tracker on another PC/Server on the same network.

### ISSUE THREAD

**Issue by joelou1** [SlimeVR/SlimeVR-Server#974]
My wife and I bought a set of 5+3 each. She started her setup and enabled her tracker. As I was doing the same, I found out that instead of adding the tracker to my list, it just stalled.
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/1740156/24d6d5ce-4c5d-4520-a76c-ccb01f442037)

Later on, we found out that my trackers were instead connected on my wife's PC/Server instead of mine, despite the Tracker being connected physically on my PC and not hers.

After communicating this in the discord server, it's been suggested that SlimeVR Server just have one instance and therefore, the first server to open is the only one to work. (Asuming they both just use the same port to work.)

This brings me to this question, how would I set MY server to a different port OR dissociate it from my network so that I can pair an use my tracker at the same time as my wife, being on her own server/PC?

Eager to recieve some help so that I don't feel like I've been cheated of a few hundred bucks.

**Comment by ImUrX** [comment]
we have fixed this in the current code but we havent released the new version yet, but we are thinking of doing it soon

This is the relevant fix if you are interested #900
