### ISSUE TITLE
macOS: Java not killed after exiting app

### ISSUE THREAD

**Issue by i0ntempest** [SlimeVR/SlimeVR-Server#989]
Running 0.11.0. After opening and quitting the server app, execute `ps -ef | grep java` in terminal:
```
  501  9051     1   0  2:08PM ??         0:03.52 /usr/bin/java -Xmx512M -jar slimevr.jar run
  501  9092  6866   0  2:08PM ttys002    0:00.00 grep --color=auto java
```
You may see that the java process was not killed. This causes the app to complain "startup error: required ports are busy" on the next run.

**Comment by ImUrX** [comment]
can you please show server and gui logs

**Comment by i0ntempest** [comment]
Where do I get those logs?

**Comment by ImUrX** [comment]
sorry forgot to answer `~/Library/Logs/dev.slimevr.SlimeVR`

**Comment by i0ntempest** [comment]
[log_last_0.log](https://github.com/SlimeVR/SlimeVR-Server/files/15241138/log_last_0.log)
[slimevr_rCURRENT.log](https://github.com/SlimeVR/SlimeVR-Server/files/15241139/slimevr_rCURRENT.log)
This was collected after after I killed java after quitting the app.

**Comment by ImUrX** [comment]
uhm, did you ever close the app? because GUI logs never say it closed...

do you have tray enabled?

**Comment by ImUrX** [comment]
probably related to https://github.com/tauri-apps/tauri/issues/9198, i suspect that Command+Q or Quit is passing as a kill command more than an ExitRequested in Tauri

**Comment by i0ntempest** [comment]
That's exactly what I just found out. It handles a click on the X button just fine but not Cmd+Q.

**Comment by ImUrX** [comment]
We need to intercept `RunEvent::Exit` then
